FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/config.py src/config.py
COPY src/drift_detector/ src/drift_detector/
COPY models/ models/
CMD ["python", "src/drift_detector/detector.py"]