FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/config.py src/config.py
COPY src/inference_worker/ src/inference_worker/
COPY models/ models/
CMD ["python", "src/inference_worker/worker.py"]