FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/config.py src/config.py
COPY src/producer/ src/producer/
CMD ["python", "src/producer/producer.py"]